import a0 from '@/assets/images/avatars/0.png';
import a1 from '@/assets/images/avatars/1.png';
import a2 from '@/assets/images/avatars/2.png';
import a3 from '@/assets/images/avatars/3.png';
import a4 from '@/assets/images/avatars/4.png';
import a5 from '@/assets/images/avatars/5.png';
import a6 from '@/assets/images/avatars/6.png';
import a7 from '@/assets/images/avatars/7.png';
import a8 from '@/assets/images/avatars/8.png';
import a9 from '@/assets/images/avatars/9.png';
import a10 from '@/assets/images/avatars/10.png';
import a11 from '@/assets/images/avatars/11.png';
import a12 from '@/assets/images/avatars/12.png';
import a13 from '@/assets/images/avatars/13.png';
import a14 from '@/assets/images/avatars/14.png';
import a15 from '@/assets/images/avatars/15.png';
import a16 from '@/assets/images/avatars/16.png';
import a17 from '@/assets/images/avatars/17.png';
import a18 from '@/assets/images/avatars/18.png';
import a19 from '@/assets/images/avatars/19.png';

export const avatars = [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19];